// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenAudio() {
  return window['go']['main']['App']['OpenAudio']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function OpenVideo() {
  return window['go']['main']['App']['OpenVideo']();
}

export function ProcessMedia(arg1) {
  return window['go']['main']['App']['ProcessMedia'](arg1);
}
