// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenAudio():Promise<string>;

export function OpenDirectory():Promise<string>;

export function OpenImage():Promise<string>;

export function OpenVideo():Promise<string>;

export function ProcessMedia(arg1:main.ProcessOptions):Promise<string>;
